/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2022.1.0.52.3
    Soft IP Version: 1.7.0
    2023 03 07 11:29:00
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module pll_osc (clki_i, clkop_o, clkos_o, clkos2_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clki_i;
    output  clkop_o;
    output  clkos_o;
    output  clkos2_o;
endmodule