/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2022.1.1.289.4
    Soft IP Version: 1.6.0
    2023 05 20 20:04:05
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module ddr_rx (rst_i, data_i, clk_i, data_o, sclk_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rst_i;
    input  [0:0]  data_i;
    input  clk_i;
    output  [1:0]  data_o;
    output  sclk_o;
endmodule